name: QA
on:
  - merge_group
  - push
  - pull_request
jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@v1.37.0
